version: "0.2"
metadata:
  name: dagster-domain-demo
  project: dagster-demo
report:
  path: ./report

domains:
  - name: hr
    incoming_dir: ./in/hr
  - name: sales
    incoming_dir: ./in/sales

entities:
  - name: employees
    domain: hr
    source:
      format: csv
      path: "{{domain.incoming_dir}}/employees.csv"
    sink:
      accepted:
        format: parquet
        path: ./out/accepted/employees
      rejected:
        format: csv
        path: ./out/rejected/employees
    policy:
      severity: reject
    schema:
      normalize_columns:
        strategy: snake_case
      columns:
        - name: employee_id
          type: string
          nullable: true
        - name: email
          type: string
        - name: is_active
          type: boolean

  - name: orders
    domain: sales
    source:
      format: csv
      path: "{{domain.incoming_dir}}/orders.csv"
    sink:
      accepted:
        format: parquet
        path: ./out/accepted/orders
      rejected:
        format: csv
        path: ./out/rejected/orders
    policy:
      severity: reject
    schema:
      normalize_columns:
        strategy: snake_case
      columns:
        - name: order_id
          type: string
          nullable: true
        - name: customer_id
          type: string
        - name: amount
          type: number

  - name: invoices
    domain: sales
    source:
      format: csv
      path: "{{domain.incoming_dir}}/invoices.csv"
    sink:
      accepted:
        format: parquet
        path: ./out/accepted/invoices
      rejected:
        format: csv
        path: ./out/rejected/invoices
    policy:
      severity: reject
    schema:
      normalize_columns:
        strategy: snake_case
      columns:
        - name: invoice_id
          type: string
          nullable: true
        - name: order_id
          type: string
        - name: total
          type: number
