version: "0.2"
metadata:
  project: "floe-airflow-example"

domains:
  - name: "hr"
    incoming_dir: "./in/hr"
  - name: "sales"
    incoming_dir: "./in/sales"

report:
  path: "./report"

entities:
  - name: "employees"
    domain: "hr"
    source:
      format: "csv"
      path: "./in/hr/employees.csv"
      options:
        header: true
        separator: ","
    sink:
      accepted:
        format: "parquet"
        path: "./out/accepted/employees"
      rejected:
        format: "csv"
        path: "./out/rejected/employees"
    policy:
      severity: "reject"
    schema:
      columns:
        - name: "employee_id"
          type: "string"
          nullable: false
          unique: true
        - name: "start_date"
          type: "date"
          nullable: false
        - name: "salary"
          type: "number"
          nullable: false

  - name: "orders"
    domain: "sales"
    source:
      format: "csv"
      path: "./in/sales/orders.csv"
      options:
        header: true
        separator: ","
    sink:
      accepted:
        format: "delta"
        path: "./out/accepted/orders_delta"
      rejected:
        format: "csv"
        path: "./out/rejected/orders"
    policy:
      severity: "reject"
    schema:
      columns:
        - name: "order_id"
          type: "string"
          nullable: false
          unique: true
        - name: "created_at"
          type: "datetime"
          nullable: false
        - name: "amount"
          type: "number"
          nullable: false
